spring.profiles.active=dev
spring.web.client.connect-timeout=20000
spring.web.client.read-timeout=20000
server.servlet.session.timeout=30s
spring.messages.always-use-message-format=false
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
spring.messages.use-code-as-default-message=false
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB
server.tomcat.max-http-form-post-size=150MB
