spring.application.name=orderproduct
server.port=8207
server.servlet.context-path=/api/v1
spring.web.client.connect-timeout=20000
spring.web.client.read-timeout=20000
server.servlet.session.timeout=30s
spring.messages.always-use-message-format=false
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
spring.messages.use-code-as-default-message=false
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB
server.tomcat.max-http-form-post-size=150MB
spring.datasource.url=jdbc:oracle:thin:@//103.27.236.135:1521/altekdb
spring.datasource.username=camid
spring.datasource.password=devalt#1235
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


config.jwt.secret.publicKey=public_key.pem
config.jwt.secret.privateKey=private_key.pem
config.jwt.secret.accessTokenExpiredTime=604800000
config.jwt.secret.refreshTokenExpiredTime=604800000

#Email sender
spring.mail.from=tranvanthinh2018sd@gmail.com
spring.mail.username=tranvanthinh2018sd
spring.mail.password=siigrccejxrksshq
spring.mail.port=587
spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

endpoint.confirmUser: http://localhost:${server.port}/user/confirm


# C?u h nh Kafka Server
spring.kafka.bootstrap-servers=localhost:9092

# C?u h nh Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# C?u h nh Consumer
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
