spring.application.name=orderproduct
server.port=1234
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orcl19
spring.datasource.username=C##MYUSER
spring.datasource.password=mypassword
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

config.jwt.secret.publicKey=public_key.pem
config.jwt.secret.privateKey=private_key.pem
config.jwt.secret.accessTokenExpiredTime=604800000
config.jwt.secret.refreshTokenExpiredTime=604800000

#Email sender
spring.mail.from=tranvanthinh2018sd@gmail.com
spring.mail.username=tranvanthinh2018sd
spring.mail.password=siigrccejxrksshq
spring.mail.port=587
spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

endpoint.confirmUser: http://localhost:${server.port}/user/confirm

